# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {F:/Curriculum de/auto_seller/project_2.cache/wt} [current_project]
set_property parent.project_path {F:/Curriculum de/auto_seller/project_2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {F:/Curriculum de/auto_seller/project_2.srcs/sources_1/imports/new/start.v}
  {F:/Curriculum de/auto_seller/project_2.srcs/sources_1/imports/new/State.v}
  {F:/Curriculum de/auto_seller/project_2.srcs/sources_1/imports/new/display.v}
  {F:/Curriculum de/auto_seller/project_2.srcs/sources_1/imports/new/main.v}
}
read_xdc {{F:/Curriculum de/auto_seller/project_2.srcs/constrs_1/imports/Verilog Lab/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{F:/Curriculum de/auto_seller/project_2.srcs/constrs_1/imports/Verilog Lab/Nexys4DDR_Master.xdc}}]

synth_design -top main -part xc7a100tcsg324-1
write_checkpoint -noxdef main.dcp
catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
